# Generated by Django 3.1.3 on 2021-01-09 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=240)),
                ('location', models.CharField(max_length=150)),
                ('snap_date', models.DateTimeField(editable=False, null=True, verbose_name='date taken')),
                ('f_number', models.FloatField(editable=False, null=True)),
                ('ISO', models.IntegerField(editable=False, null=True)),
                ('focal_length', models.IntegerField(editable=False, null=True)),
                ('shutter_speed', models.IntegerField(editable=False, null=True)),
                ('file', models.ImageField(upload_to='images')),
                ('order', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('x_min', models.FloatField()),
                ('x_max', models.FloatField()),
                ('y_min', models.FloatField()),
                ('y_max', models.FloatField()),
                ('image_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='things', to='blog.image')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('order', models.IntegerField(null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-order',),
            },
        ),
        migrations.AddField(
            model_name='image',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.post'),
        ),
        migrations.AlterUniqueTogether(
            name='image',
            unique_together={('post_id', 'order')},
        ),
    ]
