# Generated by Django 3.1.3 on 2020-11-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_image_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='file',
            field=models.ImageField(default='', upload_to='images'),
            preserve_default=False,
        ),
    ]
