# Generated by Django 3.1.3 on 2020-11-22 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_postimage_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='post_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.post'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='image',
            unique_together={('post_id', 'order')},
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
