# Generated by Django 3.1.3 on 2020-11-22 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20201122_1737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='post_id',
            new_name='post',
        ),
    ]
