# Generated by Django 3.1.3 on 2020-11-28 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20201122_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='ISO',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='f_number',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='focal_length',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='snap_date',
            field=models.DateTimeField(editable=False, null=True, verbose_name='date taken'),
        ),
        migrations.AlterUniqueTogether(
            name='image',
            unique_together={('post_id', 'order')},
        ),
    ]
