# Generated by Django 3.1.3 on 2020-12-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_thing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-order',)},
        ),
        migrations.AddField(
            model_name='post',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
